import { defineConfig } from 'vitest/config';

/** All HTML entry points for the multi-page app. */
export const HTML_ENTRIES = {
  main: 'index.html',
  favicon: 'tools/favicon/index.html',
  resize: 'tools/resize/index.html',
  crop: 'tools/crop/index.html',
  convert: 'tools/convert/index.html',
  'remove-bg': 'tools/remove-bg/index.html',
  rotate: 'tools/rotate/index.html',
  watermark: 'tools/watermark/index.html',
  blur: 'tools/blur/index.html',
  'strip-metadata': 'tools/strip-metadata/index.html',
  'og-image': 'tools/og-image/index.html',
  'app-icon': 'tools/app-icon/index.html',
  placeholder: 'tools/placeholder/index.html',
  'qr-code': 'tools/qr-code/index.html',
  palette: 'tools/palette/index.html',
  padding: 'tools/padding/index.html',
  mask: 'tools/mask/index.html',
  adjust: 'tools/adjust/index.html',
  combine: 'tools/combine/index.html',
  base64: 'tools/base64/index.html',
  'svg-to-png': 'tools/svg-to-png/index.html',
  'sprite-sheet': 'tools/sprite-sheet/index.html',
  'favicon-checker': 'tools/favicon-checker/index.html',
  'manifest-builder': 'tools/manifest-builder/index.html',
  'html-snippet': 'tools/html-snippet/index.html',
  'metadata-viewer': 'tools/metadata-viewer/index.html',
  'screenshot-sanitizer': 'tools/screenshot-sanitizer/index.html',
  compare: 'tools/compare/index.html',
  'trim-alpha': 'tools/trim-alpha/index.html',
  'dataurl-decode': 'tools/dataurl-decode/index.html',
  'bulk-resize': 'tools/bulk-resize/index.html',
  'splash-screen': 'tools/splash-screen/index.html',
  'maskable-preview': 'tools/maskable-preview/index.html',
  duotone: 'tools/duotone/index.html',
  'contrast-checker': 'tools/contrast-checker/index.html',
  'social-card': 'tools/social-card/index.html',
  'icon-checker': 'tools/icon-checker/index.html',
  'file-inspector': 'tools/file-inspector/index.html',
  'css-filters': 'tools/css-filters/index.html',
  'split-image': 'tools/split-image/index.html',
  'gif-maker': 'tools/gif-maker/index.html',
  'pdf-to-image': 'tools/pdf-to-image/index.html',
  'image-to-pdf': 'tools/image-to-pdf/index.html',
  sharpen: 'tools/sharpen/index.html',
  'tile-preview': 'tools/tile-preview/index.html',
} as const;

export default defineConfig({
  base: './',
  build: {
    outDir: 'dist',
    sourcemap: true,
    rollupOptions: {
      input: HTML_ENTRIES,
    },
  },
  test: {
    environment: 'happy-dom',
    include: ['src/**/*.test.ts'],
  },
});
